---
# lxc-docker is the default
docker_pkg_name: lxc-docker

# default file
docker_defaults_file_path: /etc/default/docker

ssh_port: 22

# Place to get apt repository key
apt_key_url: http://get.docker.io/gpg

# apt repository key signature
apt_key_sig: A88D21E9

# Name of the apt repository for docker
apt_repository: deb https://get.docker.com/ubuntu docker main
# The followinag help expose a docker port or to add additional options when
# running docker daemon.  The default is to not use any special options.
#docker_opts: >
#  -H unix://
#  -H tcp://0.0.0.0:2375
#  --log-level=debug
docker_opts: "-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock --insecure-registry registry.rosscousens.com:5000"

# List of users to be added to 'docker' system group (disabled by default)
# SECURITY WARNING:
# Be aware that granted users can easily get full root access on the docker host system!
docker_group_members: []

# Versions for the python packages that are installed installed
pip_version_pip: latest
pip_version_setuptools: latest
pip_version_docker_py: latest
pip_version_docker_compose: latest

# Set to 'yes' or 'true' to enable updates (sets 'latest' in apt module)
update_docker_package: no
