---
- name: Container Storage Directory
  file:
    path: /data
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Docker Registry Container
  docker:
    name: registry
    image: registry:2
    state: started
    restart_policy: always
    volumes:
      - /data:/var/lib/registry
    ports:
      - 5000:5000
